In [14]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5, 6])
vector = vector -4
matrix = vector.reshape((2,3))
matrix = matrix * matrix
matrix = matrix[:, :2]
matrix = matrix - np.eye(2)
matrix = matrix.T
matrix[0, 0] = 0
matrix[1, 0] = 0
print(matrix)

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

vector = np.array([2, 6, 10, 0, 4, 2])
vector = vector * 0.5
matrix = vector.reshape((3,2))
matrix = matrix * matrix - matrix
matrix = matrix[:2, :]
matrix = matrix + 6*np.eye(2)
matrix = matrix.T
matrix[0,1]=6.
print(matrix)

[[6. 6.]
 [6. 6.]]


In [3]:
import numpy as np

vector = np.array([4, 8, 12, 4, 8, 12])
vector = vector * 0.25
matrix = vector.reshape((3,2))
matrix = matrix * matrix - matrix
matrix = matrix[:2, :]
matrix = matrix - 6*np.eye(2)
matrix = matrix.T.T.T
matrix[1,0]=6.
print(matrix)

[[-6.  6.]
 [ 6. -6.]]


In [4]:
import numpy as np

vector = np.array([-1, -4, -5, 2, 3, 1])
vector = vector + 1
matrix = vector.reshape((2,3))
matrix = (matrix - 3) * (matrix -3)
matrix = matrix[:, :2]
matrix = matrix - np.eye(2)
matrix = matrix.T.T.T.T
print(matrix)

[[ 8. 36.]
 [ 0.  0.]]
