## Numpy

1. Создайте вектор состоящий из чисел от 0 до 11 включительно. 

In [2]:
import numpy as np
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


2. Измените размерность вектора и превратите его в матрицу 3 х 4

In [3]:
a=a.reshape((3,4))
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


3. Найдите произведение полученной матрицы и вектора [2, 3, 5, 6]

In [4]:
b=[2,3,5,6]
print(a.dot(b))

[ 31  95 159]


4. Из матрицы из пункта 2 сделайте квадратную матрицу состоящую из строк с индексами 0, 1, 3

In [5]:
c=a[:,:3]
c[:,2]=a[:,3]

5. Найдите обратную матрицу к полученной в пункте 4.

In [6]:
 c=c.T

6. Проверьте является ли она обратной?

In [7]:
m=np.matrix([c[0,:],c[1,:],c[2,:]])
m.I

LinAlgError: Singular matrix

## Pandas

1. Загрузите данные из https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv в DataFrame. Воспользуйтесь одним из способов предложенных на занятии.

In [8]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

2. Выведите несколько первых строк таблицы. 

In [9]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

3. Отфильруйте машины по марке и оставьте только строки с автомобилями BMW. 

In [10]:
BMW =df[df.Make=='BMW']

4. Найдите среднюю стоимость автомобиля BMW и выведите данное значение с точность до двух знаком после запятой.

In [11]:
arr=np.array(BMW.MSRP)
round(arr.mean(),2)

61546.76

5. Определите каких автомобилей больше с ручной коробокой передач или автоматической?

In [23]:
Ma=df[df['Transmission Type']=='MANUAL']
Au=df[df['Transmission Type']=='AUTOMATIC']
if len(Ma)-len(Au)<0:
    print("Автомобилей с автоматической больше чем с ручной коробокой передач")
elif len(Ma)-len(Au)>0:
     print("Автомобилей с ручной коробокой больше чем с автоматической передач")
else :
    print("Автомобилей с ручной коробокой равно автомобилей с автоматической передач")

Автомобилей с автоматической больше чем с ручной коробокой передач
